"""llms.txt link parsing and dump / curation classification."""

from __future__ import annotations

import time
import unittest

import aio_heuristics as heuristics

CURATED = "# Site\n\n> Summary.\n\n## Docs\n\n- [A](https://x.example/a): About A.\n"


def links(count: int, bullet: str = "-") -> str:
    return "".join(f"{bullet} [P{n}](https://x.example/p{n}): Page {n}.\n" for n in range(count))


class LinkLineTests(unittest.TestCase):
    def parse(self, line: str) -> tuple[str, str, str] | None:
        match = heuristics.LLMS_LINK_RE.fullmatch(line)
        return match.groups() if match else None

    def test_parses_the_proposal_shape(self) -> None:
        self.assertEqual(
            self.parse("- [Title](https://x.example/a): Notes here."),
            ("Title", "https://x.example/a", "Notes here."),
        )

    def test_notes_are_optional(self) -> None:
        self.assertEqual(self.parse("- [Title](https://x.example/a)"), ("Title", "https://x.example/a", ""))

    def test_accepts_common_markdown_variations(self) -> None:
        for line, url in (
            ("* [T](https://x.example/a): n", "https://x.example/a"),
            ("+ [T](https://x.example/a)", "https://x.example/a"),
            ("  - [T](https://x.example/a): n", "https://x.example/a"),
            ("- [T [beta]](https://x.example/a): n", "https://x.example/a"),
            ("- [T](https://x.example/wiki/A_(b)): n", "https://x.example/wiki/A_(b)"),
            ('- [T](https://x.example/a "Tooltip"): n', "https://x.example/a"),
            ("- [T](<https://x.example/a>): n", "https://x.example/a"),
            ("- [T](https://x.example/a) - n", "https://x.example/a"),
            ("- [T](https://x.example/a) — n", "https://x.example/a"),
        ):
            with self.subTest(line=line):
                parsed = self.parse(line)
                self.assertIsNotNone(parsed)
                self.assertEqual(parsed[1], url)

    def test_ignores_non_link_lines(self) -> None:
        for line in ("- plain bullet", "Some [inline](https://x.example/) link", "* * *", "## Heading"):
            with self.subTest(line=line):
                self.assertIsNone(self.parse(line))

    def test_hostile_line_is_matched_in_bounded_time(self) -> None:
        for line in ("- [" + "[" * 50_000, "- [T](" + "(" * 50_000, "- [T](https://x/" + "a(" * 50_000):
            started = time.monotonic()
            heuristics.LLMS_LINK_RE.fullmatch(line)
            self.assertLess(time.monotonic() - started, 2.0)


class DumpSignalsTests(unittest.TestCase):
    def test_total_link_threshold(self) -> None:
        at_limit = "## A\n" + links(10) + "## B\n" + links(heuristics.MAX_TOTAL_LINKS - 10)
        over_limit = at_limit + "## C\n- [X](https://x.example/x)\n"

        self.assertEqual(heuristics.dump_signals(at_limit), [])
        self.assertIn(f"too-many-links:{heuristics.MAX_TOTAL_LINKS + 1}", heuristics.dump_signals(over_limit))

    def test_section_link_threshold(self) -> None:
        self.assertEqual(heuristics.dump_signals("## A\n" + links(heuristics.MAX_SECTION_LINKS)), [])
        self.assertEqual(
            heuristics.dump_signals("## A\n" + links(heuristics.MAX_SECTION_LINKS + 1)),
            ["oversized-section"],
        )

    def test_oversized_section_is_reported_once(self) -> None:
        text = "## A\n" + links(13) + "## B\n" + links(13)

        self.assertEqual(heuristics.dump_signals(text).count("oversized-section"), 1)

    def test_star_bullet_dump_is_detected(self) -> None:
        signals = heuristics.dump_signals("## Posts\n" + links(30, bullet="*"))

        self.assertEqual(signals, ["too-many-links:30", "oversized-section"])

    def test_plugin_markers(self) -> None:
        self.assertEqual(
            heuristics.dump_signals("# Generated by Rank Math SEO\n\n## Sitemaps\n"),
            ["rank-math-preamble", "sitemaps-section"],
        )


class ClassifyLlmsTests(unittest.TestCase):
    def test_each_class(self) -> None:
        for text, status, expected in (
            (CURATED, 200, "curated"),
            (CURATED, None, "curated"),
            (None, 404, "missing"),
            (None, 410, "missing"),
            (None, None, "missing"),
            ("  \n", 200, "empty"),
            ("# Site\n> s\n## A\n" + links(30), 200, "dump"),
            ("no heading\n> s\n## A\n", 200, "malformed"),
            ("# Site\n\n## A\n", 200, "malformed"),
            ("# Site\n> s\n", 200, "malformed"),
        ):
            with self.subTest(expected=expected, status=status):
                self.assertEqual(heuristics.classify_llms(text, status_code=status), expected)

    def test_error_status_is_never_classified_from_its_body(self) -> None:
        for status, body in ((500, CURATED), (403, "<html>blocked</html>"), (503, None)):
            with self.subTest(status=status):
                self.assertEqual(heuristics.classify_llms(body, status_code=status), "unavailable")

    def test_byte_order_mark_is_tolerated(self) -> None:
        self.assertEqual(heuristics.classify_llms("﻿" + CURATED, status_code=200), "curated")


class LinkHelpersTests(unittest.TestCase):
    def test_absolute_https_links_skips_other_schemes(self) -> None:
        text = "- [A](https://x.example/a)\n- [B](http://x.example/b)\n- [C](/relative)\n"

        self.assertEqual(heuristics.absolute_https_links(text), ["https://x.example/a"])

    def test_markdown_variant_links(self) -> None:
        urls = [
            "https://x.example/a/index.html.md",
            "https://x.example/b.MD?x=1#frag",
            "https://x.example/c/",
            "https://x.example/readme.md.html",
        ]

        self.assertEqual(heuristics.markdown_variant_links(urls), urls[:2])


if __name__ == "__main__":
    unittest.main()
