#!/usr/bin/env python3
"""Shared llms.txt dump / curation heuristics (no network)."""

from __future__ import annotations

import re
from urllib.parse import urlparse

LLMS_LINK_RE = re.compile(r"^- \[([^\]]+)\]\(([^)]+)\)(?::\s*(.*))?$")


def dump_signals(text: str) -> list[str]:
    """Heuristics that mark an SEO-plugin / sitemap-style llms.txt dump."""
    signals: list[str] = []
    lowered = text.lower()
    if "generated by rank math" in lowered or "rank math seo" in lowered:
        signals.append("rank-math-preamble")
    if re.search(r"^##\s+Sitemaps\s*$", text, re.MULTILINE | re.IGNORECASE):
        signals.append("sitemaps-section")

    link_count = sum(1 for line in text.splitlines() if LLMS_LINK_RE.fullmatch(line))
    if link_count > 20:
        signals.append(f"too-many-links:{link_count}")

    section_links = 0
    for line in text.splitlines():
        if line.startswith("## "):
            if section_links > 12:
                signals.append("oversized-section")
                break
            section_links = 0
        elif LLMS_LINK_RE.fullmatch(line):
            section_links += 1
    else:
        if section_links > 12:
            signals.append("oversized-section")
    return signals


def classify_llms(text: str | None, *, status_code: int | None = None) -> str:
    """Return missing | empty | dump | curated | malformed."""
    if status_code == 404 or text is None:
        return "missing"
    if not text.strip():
        return "empty"
    if dump_signals(text):
        return "dump"
    if not text.lstrip().startswith("# "):
        return "malformed"
    if not re.search(r"^> \S", text, re.MULTILINE):
        return "malformed"
    if "## " not in text:
        return "malformed"
    return "curated"


def absolute_https_links(text: str) -> list[str]:
    urls: list[str] = []
    for line in text.splitlines():
        match = LLMS_LINK_RE.fullmatch(line)
        if not match:
            continue
        url = match.group(2)
        parsed = urlparse(url)
        if parsed.scheme == "https" and parsed.netloc:
            urls.append(url)
    return urls
